package main

import (
	"text/template"

	"github.com/spf13/cobra"
)

type item struct {
	Name string `json:"name"`
	ID   int    `json:"id"`
}

func (i item) Ident() string {
	return ident(i.Name)
}

var itemSource = template.Must(template.New("items").Parse(
	`// Code generated by gen items {{.Version}}; DO NOT EDIT.

package items

import gocraft "github.com/lrnxzz/go-craft"

const (
{{- range .Entries}}
	{{.Ident}} gocraft.ItemID = {{.ID}}
{{- end}}
)
`))

func itemsCommand() *cobra.Command {
	return generator[item]{
		name:     "items",
		asset:    "items.json",
		output:   "items.go",
		template: itemSource,
	}.command()
}
