package main

import (
	"text/template"

	"github.com/spf13/cobra"
)

type materialSpeeds map[string]map[int]float64

var materialSource = template.Must(template.New("materials").Parse(
	`// Code generated by gen materials {{.Version}}; DO NOT EDIT.

package blocks

var materials = map[string]toolSpeeds{
{{- range $material, $tools := .Entries}}
	"{{$material}}": {
{{- range $item, $speed := $tools}}
		{{$item}}: {{$speed}},
{{- end}}
	},
{{- end}}
}
`))

func materialsCommand() *cobra.Command {
	return generator[materialSpeeds]{
		name:     "materials",
		asset:    "materials.json",
		output:   "materials.go",
		template: materialSource,
	}.command()
}
