// Code generated by gen biomes 765; DO NOT EDIT.

package biomes

import gocraft "github.com/lrnxzz/go-craft"

const (
	Badlands               gocraft.Biome = 0
	BambooJungle           gocraft.Biome = 1
	BasaltDeltas           gocraft.Biome = 2
	Beach                  gocraft.Biome = 3
	BirchForest            gocraft.Biome = 4
	CherryGrove            gocraft.Biome = 5
	ColdOcean              gocraft.Biome = 6
	CrimsonForest          gocraft.Biome = 7
	DarkForest             gocraft.Biome = 8
	DeepColdOcean          gocraft.Biome = 9
	DeepDark               gocraft.Biome = 10
	DeepFrozenOcean        gocraft.Biome = 11
	DeepLukewarmOcean      gocraft.Biome = 12
	DeepOcean              gocraft.Biome = 13
	Desert                 gocraft.Biome = 14
	DripstoneCaves         gocraft.Biome = 15
	EndBarrens             gocraft.Biome = 16
	EndHighlands           gocraft.Biome = 17
	EndMidlands            gocraft.Biome = 18
	ErodedBadlands         gocraft.Biome = 19
	FlowerForest           gocraft.Biome = 20
	Forest                 gocraft.Biome = 21
	FrozenOcean            gocraft.Biome = 22
	FrozenPeaks            gocraft.Biome = 23
	FrozenRiver            gocraft.Biome = 24
	Grove                  gocraft.Biome = 25
	IceSpikes              gocraft.Biome = 26
	JaggedPeaks            gocraft.Biome = 27
	Jungle                 gocraft.Biome = 28
	LukewarmOcean          gocraft.Biome = 29
	LushCaves              gocraft.Biome = 30
	MangroveSwamp          gocraft.Biome = 31
	Meadow                 gocraft.Biome = 32
	MushroomFields         gocraft.Biome = 33
	NetherWastes           gocraft.Biome = 34
	Ocean                  gocraft.Biome = 35
	OldGrowthBirchForest   gocraft.Biome = 36
	OldGrowthPineTaiga     gocraft.Biome = 37
	OldGrowthSpruceTaiga   gocraft.Biome = 38
	Plains                 gocraft.Biome = 39
	River                  gocraft.Biome = 40
	Savanna                gocraft.Biome = 41
	SavannaPlateau         gocraft.Biome = 42
	SmallEndIslands        gocraft.Biome = 43
	SnowyBeach             gocraft.Biome = 44
	SnowyPlains            gocraft.Biome = 45
	SnowySlopes            gocraft.Biome = 46
	SnowyTaiga             gocraft.Biome = 47
	SoulSandValley         gocraft.Biome = 48
	SparseJungle           gocraft.Biome = 49
	StonyPeaks             gocraft.Biome = 50
	StonyShore             gocraft.Biome = 51
	SunflowerPlains        gocraft.Biome = 52
	Swamp                  gocraft.Biome = 53
	Taiga                  gocraft.Biome = 54
	TheEnd                 gocraft.Biome = 55
	TheVoid                gocraft.Biome = 56
	WarmOcean              gocraft.Biome = 57
	WarpedForest           gocraft.Biome = 58
	WindsweptForest        gocraft.Biome = 59
	WindsweptGravellyHills gocraft.Biome = 60
	WindsweptHills         gocraft.Biome = 61
	WindsweptSavanna       gocraft.Biome = 62
	WoodedBadlands         gocraft.Biome = 63
)
