// Code generated by gen biomes 765; DO NOT EDIT.

package biomes

import gocraft "github.com/lrnxzz/go-craft"

const (
	Badlands               gocraft.BiomeID = 0
	BambooJungle           gocraft.BiomeID = 1
	BasaltDeltas           gocraft.BiomeID = 2
	Beach                  gocraft.BiomeID = 3
	BirchForest            gocraft.BiomeID = 4
	CherryGrove            gocraft.BiomeID = 5
	ColdOcean              gocraft.BiomeID = 6
	CrimsonForest          gocraft.BiomeID = 7
	DarkForest             gocraft.BiomeID = 8
	DeepColdOcean          gocraft.BiomeID = 9
	DeepDark               gocraft.BiomeID = 10
	DeepFrozenOcean        gocraft.BiomeID = 11
	DeepLukewarmOcean      gocraft.BiomeID = 12
	DeepOcean              gocraft.BiomeID = 13
	Desert                 gocraft.BiomeID = 14
	DripstoneCaves         gocraft.BiomeID = 15
	EndBarrens             gocraft.BiomeID = 16
	EndHighlands           gocraft.BiomeID = 17
	EndMidlands            gocraft.BiomeID = 18
	ErodedBadlands         gocraft.BiomeID = 19
	FlowerForest           gocraft.BiomeID = 20
	Forest                 gocraft.BiomeID = 21
	FrozenOcean            gocraft.BiomeID = 22
	FrozenPeaks            gocraft.BiomeID = 23
	FrozenRiver            gocraft.BiomeID = 24
	Grove                  gocraft.BiomeID = 25
	IceSpikes              gocraft.BiomeID = 26
	JaggedPeaks            gocraft.BiomeID = 27
	Jungle                 gocraft.BiomeID = 28
	LukewarmOcean          gocraft.BiomeID = 29
	LushCaves              gocraft.BiomeID = 30
	MangroveSwamp          gocraft.BiomeID = 31
	Meadow                 gocraft.BiomeID = 32
	MushroomFields         gocraft.BiomeID = 33
	NetherWastes           gocraft.BiomeID = 34
	Ocean                  gocraft.BiomeID = 35
	OldGrowthBirchForest   gocraft.BiomeID = 36
	OldGrowthPineTaiga     gocraft.BiomeID = 37
	OldGrowthSpruceTaiga   gocraft.BiomeID = 38
	Plains                 gocraft.BiomeID = 39
	River                  gocraft.BiomeID = 40
	Savanna                gocraft.BiomeID = 41
	SavannaPlateau         gocraft.BiomeID = 42
	SmallEndIslands        gocraft.BiomeID = 43
	SnowyBeach             gocraft.BiomeID = 44
	SnowyPlains            gocraft.BiomeID = 45
	SnowySlopes            gocraft.BiomeID = 46
	SnowyTaiga             gocraft.BiomeID = 47
	SoulSandValley         gocraft.BiomeID = 48
	SparseJungle           gocraft.BiomeID = 49
	StonyPeaks             gocraft.BiomeID = 50
	StonyShore             gocraft.BiomeID = 51
	SunflowerPlains        gocraft.BiomeID = 52
	Swamp                  gocraft.BiomeID = 53
	Taiga                  gocraft.BiomeID = 54
	TheEnd                 gocraft.BiomeID = 55
	TheVoid                gocraft.BiomeID = 56
	WarmOcean              gocraft.BiomeID = 57
	WarpedForest           gocraft.BiomeID = 58
	WindsweptForest        gocraft.BiomeID = 59
	WindsweptGravellyHills gocraft.BiomeID = 60
	WindsweptHills         gocraft.BiomeID = 61
	WindsweptSavanna       gocraft.BiomeID = 62
	WoodedBadlands         gocraft.BiomeID = 63
)
